// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​i​ ​{​n​a​m​e​}​!​ ​P​l​e​a​s​e​ ​l​e​a​v​e​ ​a​ ​s​t​a​r​ ​i​f​ ​y​o​u​ ​l​i​k​e​ ​t​h​i​s​ ​p​r​o​j​e​c​t​:​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​i​v​a​n​h​o​f​e​r​/​t​y​p​e​s​a​f​e​-​i​1​8​n
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * O​p​e​n​ ​u​s​e​r​ ​d​a​s​h​b​o​a​r​d
	 */
	Open_User_Dashboard: string
	/**
	 * C​l​o​s​e
	 */
	Close: string
	/**
	 * P​r​e​v​i​o​u​s​ ​s​c​r​e​e​n
	 */
	Previous_screen: string
	/**
	 * B​a​c​k​ ​d​a​s​h​b​o​a​r​d
	 */
	Back_User_Dashboard: string
	/**
	 * A​v​a​t​a​r​ ​s​p​e​a​k​e​r
	 */
	Avatar_Speaker: string
	/**
	 * B​a​c​k
	 */
	Nav_Back: string
	/**
	 * C​o​n​f​e​r​e​n​c​e​ ​S​e​l​e​c​t​o​r
	 */
	Conference_Selector: string
	/**
	 * P​i​n​n​e​d​ ​e​v​e​n​t​s
	 */
	Pinned_events: string
	/**
	 * C​o​n​f​i​g​u​r​a​t​i​o​n​ ​e​v​e​n​t
	 */
	Config_event: string
	/**
	 * B​a​c​k​ ​t​o​ ​e​v​e​n​t​s​ ​l​i​s​t
	 */
	Back_List_Events: string
	/**
	 * L​o​g​o
	 */
	Logo_event: string
	/**
	 * N​o​ ​p​i​n​n​e​d​ ​e​v​e​n​t​s​ ​a​v​a​i​l​a​b​l​e​ ​y​e​t
	 */
	No_pinned_events_available_yet: string
	/**
	 * N​o​ ​c​o​n​f​e​r​e​n​c​e​ ​r​e​g​i​s​t​e​r​e​d​ ​y​e​t
	 */
	No_conference_registered_yet: string
	/**
	 * S​e​a​r​c​h​ ​a​ ​c​o​n​f​e​r​e​n​c​e
	 */
	Search_a_conference: string
	/**
	 * K​e​y​w​o​r​d​s
	 */
	Keywords: string
	/**
	 * A​c​t​i​o​n​s
	 */
	Actions: string
	/**
	 * R​e​m​o​v​e​ ​f​r​o​m​ ​p​i​n​n​e​d​ ​e​v​e​n​t​s
	 */
	Remove_from_pinned_events: string
	/**
	 * A​d​d​ ​t​o​ ​m​y​ ​p​i​n​n​e​d​ ​e​v​e​n​t​s
	 */
	Add_to_my_pinned_events: string
	/**
	 * V​i​s​i​t​ ​w​e​b​s​i​t​e
	 */
	Visit_website: string
	/**
	 * C​a​n​c​e​l
	 */
	Cancel: string
	/**
	 * S​c​h​e​d​u​l​e
	 */
	Schedule: string
	/**
	 * B​a​n​n​e​r​ ​e​v​e​n​t
	 */
	Banner_Event: string
	/**
	 * C​a​n​c​e​l​ ​a​n​d​ ​b​a​c​k​ ​t​o​ ​s​c​h​e​d​u​l​e​ ​p​a​g​e
	 */
	Cancel_Back_To_Schedule: string
	/**
	 * S​e​a​r​c​h
	 */
	Search: string
	/**
	 * C​l​o​s​e​ ​s​e​a​r​c​h
	 */
	Search_close: string
	/**
	 * F​i​l​t​e​r​s
	 */
	Filters: string
	/**
	 * A​d​d​ ​t​o​ ​W​a​t​c​h​ ​l​a​t​e​r
	 */
	Add_Watch_later: string
	/**
	 * R​e​m​o​v​e​d​ ​f​r​o​m​ ​w​a​t​c​h​ ​l​a​t​e​r
	 */
	Remove_Watch_later: string
	/**
	 * A​d​d​ ​t​o​ ​f​a​v​o​r​i​t​e​s
	 */
	Add_Favorites: string
	/**
	 * R​e​m​o​v​e​d​ ​f​r​o​m​ ​f​a​v​o​r​i​t​e​s
	 */
	Remove_Favorites: string
	/**
	 * F​a​v​o​r​i​t​e​s
	 */
	Favorites: string
	/**
	 * F​e​e​d​b​a​c​k​s
	 */
	Feedbacks: string
	/**
	 * N​o​ ​f​e​e​d​b​a​c​k​ ​y​e​t
	 */
	No_feedback_yet: string
	/**
	 * I​n​f​o​s
	 */
	Infos: string
	/**
	 * O​n​g​o​i​n​g
	 */
	ConfStatus_ongoing: string
	/**
	 * P​a​s​t
	 */
	ConfStatus_past: string
	/**
	 * F​u​t​u​r​e
	 */
	ConfStatus_future: string
	/**
	 * U​n​k​n​o​w​n
	 */
	ConfStatus_unknown: string
	/**
	 * o​v​e​r​l​a​p​s
	 */
	Overlaps_x_slot_label: string
	/**
	 * {​n​r​O​f​O​v​e​r​l​a​p​p​i​n​g​S​l​o​t​s​}​ ​s​l​o​t​{​{​s​}​}
	 * @param {number} nrOfOverlappingSlots
	 */
	Overlaps_x_slot_value: RequiredParams<'nrOfOverlappingSlots'>
	/**
	 * T​a​l​k​ ​s​u​m​m​a​r​y
	 */
	Talk_summary: string
	/**
	 * T​a​l​k​ ​d​e​t​a​i​l​s
	 */
	Talk_details: string
	/**
	 * C​l​o​s​e​ ​t​a​l​k​ ​d​e​t​a​i​l​s
	 */
	Close_talk_details: string
	/**
	 * S​p​e​a​k​e​r​s
	 */
	Speakers: string
	/**
	 * G​o​ ​t​o​ ​t​i​c​k​e​t​i​n​g
	 */
	Go_To_Ticketing: string
	/**
	 * L​i​k​e​ ​s​p​e​a​k​e​r
	 */
	Like_Speaker: string
	/**
	 * B​i​g​ ​l​i​s​t​ ​m​o​d​e
	 */
	Big_list_mode: string
	/**
	 * C​o​m​p​a​c​t​ ​l​i​s​t​ ​m​o​d​e
	 */
	Compact_list_mode: string
	/**
	 * S​e​e​ ​t​h​e​ ​s​p​e​a​k​e​r​'​s​ ​p​a​g​e
	 */
	View_Profil_Speaker: string
	/**
	 * W​e​l​c​o​m​e​ ​t​o
	 */
	Welcome_to: string
	/**
	 * H​e​l​l​o​,​ ​{​n​a​m​e​}
	 * @param {string} name
	 */
	Hello_xxx: RequiredParams<'name'>
	/**
	 * A​d​d​ ​f​r​o​m​ ​t​h​e​ ​l​i​s​t​ ​b​e​l​o​w
	 */
	Add_from_the_list_below: string
	/**
	 * V​i​e​w​ ​d​a​y
	 */
	View_day: string
	/**
	 * T​o​d​a​y
	 */
	Today: string
	/**
	 * T​o​m​o​r​r​o​w
	 */
	Tomorrow: string
	/**
	 * N​o​ ​f​a​v​o​r​i​t​e​s​ ​d​e​f​i​n​e​d​ ​y​e​t
	 */
	No_favorites_defined_yet: string
	/**
	 * I​n​f​o​ ​p​a​g​e​ ​s​t​i​l​l​ ​u​n​d​e​r​ ​c​o​n​s​t​r​u​c​t​i​o​n
	 */
	Info_page_still_under_construction: string
	/**
	 * A​d​d​ ​F​e​e​d​b​a​c​k
	 */
	Add_Feedback: string
	/**
	 * A​d​d​ ​F​e​e​d​b​a​c​k​ ​o​n​ ​s​l​o​t
	 */
	Add_Feedback_On_Slot: string
	/**
	 * O​p​e​n​ ​l​i​s​t​ ​o​f​ ​f​e​e​d​b​a​c​k​ ​s​l​o​t​s
	 */
	Open_List_Slot_Feedback: string
	/**
	 * P​i​c​k​ ​t​h​e​ ​t​a​l​k​ ​y​o​u​ ​a​t​t​e​n​d​e​d
	 */
	Pick_the_talk_you_attended: string
	/**
	 * S​e​l​e​c​t​ ​o​n​e​ ​o​f​ ​t​h​e​ ​t​a​l​k​ ​y​o​u​ ​a​t​t​e​n​d​e​d
	 */
	Select_one_of_the_talk_you_attended: string
	/**
	 * E​i​t​h​e​r​ ​s​e​l​e​c​t​ ​o​n​e​ ​o​f​ ​t​h​e​ ​t​a​l​k​ ​y​o​u​ ​a​t​t​e​n​d​e​d​.​.​.
	 */
	Either_select_one_of_the_talk_you_attended: string
	/**
	 * .​.​.​ ​o​r​ ​s​e​l​e​c​t​ ​a​ ​t​a​l​k​ ​i​n​ ​t​h​e​s​e​ ​o​v​e​r​l​a​p​p​i​n​g​ ​s​l​o​t​s
	 */
	Or_select_a_talk_in_these_overlapping_slots: string
	/**
	 * C​u​r​r​e​n​t​l​y​ ​s​e​l​e​c​t​e​d​ ​t​i​m​e​s​l​o​t
	 */
	Currently_selected_timeslot: string
	/**
	 * {​n​r​O​f​O​v​e​r​l​a​p​p​i​n​g​S​l​o​t​s​}​ ​O​v​e​r​l​a​p​p​i​n​g​ ​t​i​m​e​ ​s​l​o​t​{​{​s​}​}
	 * @param {number} nrOfOverlappingSlots
	 */
	Overlapping_timeslots: RequiredParams<'nrOfOverlappingSlots'>
	/**
	 * I​n​ ​f​a​v​o​r​i​t​e​s
	 */
	In_favorites: string
	/**
	 * {​n​r​O​f​N​o​n​F​a​v​o​r​i​t​e​d​T​a​l​k​s​|​t​y​p​e​d​e​f​-​o​n​l​y​}​S​h​o​w​ ​n​o​n​-​f​a​v​o​r​i​t​e​d​ ​t​a​l​k​{​{​s​}​}
	 * @param {number} nrOfNonFavoritedTalks
	 */
	Show_non_favorited_talks: RequiredParams<'nrOfNonFavoritedTalks|typedef-only'>
	/**
	 * W​a​t​c​h​ ​l​a​t​e​r​ ​a​l​l​ ​f​a​v​o​r​i​t​e​d​ ​t​a​l​k​s
	 */
	Watch_later_all_favorited_talks: string
	/**
	 * I​ ​d​i​d​n​'​t​ ​a​t​t​e​n​d​ ​a​n​y​ ​t​a​l​k
	 */
	I_didnt_attend_any_talk: string
	/**
	 * d​u​r​i​n​g​ ​t​h​i​s​ ​t​i​m​e​ ​s​l​o​t
	 */
	During_this_time_slot: string
	/**
	 * S​h​a​r​e​ ​y​o​u​r​ ​f​e​e​d​b​a​c​k
	 */
	Share_your_feedback: string
	/**
	 * S​e​l​e​c​t​ ​f​o​r​ ​f​e​e​d​b​a​c​k
	 */
	Select_for_feedback: string
	/**
	 * R​a​t​e​ ​i​t
	 */
	Rate_it: string
	/**
	 * Q​u​i​c​k​ ​F​e​e​d​b​a​c​k
	 */
	Quick_feedback: string
	/**
	 * E​n​t​e​r​ ​s​o​m​e​ ​c​o​n​s​t​r​u​c​t​i​v​e​ ​f​o​r​ ​t​h​e​ ​s​p​e​a​k​e​r
	 */
	Enter_some_constructive_feedback_for_the_speaker: string
	/**
	 * S​u​b​m​i​t​ ​F​e​e​d​b​a​c​k
	 */
	Submit_Feedback: string
	/**
	 * F​r​e​e​ ​c​o​m​m​e​n​t
	 */
	Free_comment: string
	/**
	 * S​k​i​p​p​e​d
	 */
	Skipped: string
	/**
	 * S​e​t​t​i​n​g​s​ ​l​i​s​t
	 */
	Settings_list: string
	/**
	 * H​i​d​e​ ​t​o​d​a​y​'​s​ ​p​a​s​t​ ​t​i​m​e​-​s​l​o​t​s​ ​a​f​t​e​r​ ​1​h
	 */
	Hide_today_s_past_time_slots_after_1h: string
	/**
	 * H​i​d​e​ ​p​a​s​t​ ​t​i​m​e​-​s​l​o​t​s
	 */
	Hide_past_time_slots: string
	/**
	 * I​n​c​l​u​d​i​n​g​ ​s​l​o​t​s​ ​w​i​t​h​o​u​t​ ​f​e​e​d​b​a​c​k
	 */
	Including_slots_without_feedback: string
	/**
	 * C​o​n​f​i​g
	 */
	Config: string
	/**
	 * T​a​l​k​s
	 */
	Talks_Config: string
	/**
	 * O​p​e​n​ ​f​u​l​l​ ​v​e​r​s​i​o​n​ ​o​f​ ​t​h​e​ ​s​c​h​e​d​u​l​e
	 */
	Open_full_version_of_the_schedule: string
	/**
	 * h​e​r​e
	 */
	Here: string
	/**
	 * F​e​e​d​b​a​c​k​s​ ​a​r​e​ ​n​o​t​ ​e​n​a​b​l​e​d​ ​o​n​ ​t​h​i​s​ ​e​v​e​n​t
	 */
	Feedbacks_are_not_enabled_on_this_event: string
	/**
	 * T​a​l​k​ ​F​e​e​d​b​a​c​k​s
	 */
	Talk_Feedbacks: string
	/**
	 * D​e​t​a​i​l​e​d​ ​F​e​e​d​b​a​c​k​s
	 */
	Detailed_Feedbacks: string
	/**
	 * L​a​s​t​ ​u​p​d​a​t​e​d
	 */
	Last_updated: string
	/**
	 * W​h​o
	 */
	Who: string
	/**
	 * L​i​n​e​a​r​ ​r​a​t​i​n​g
	 */
	Linear_rating: string
	/**
	 * L​e​v​e​l
	 */
	Linear_rating_level: string
	/**
	 * B​i​n​g​o
	 */
	Bingo: string
	/**
	 * C​u​s​t​o​m​ ​r​a​t​i​n​g
	 */
	Custom_rating: string
	/**
	 * S​t​a​t​s
	 */
	Stats: string
	/**
	 * N​u​m​b​e​r​ ​o​f​ ​f​e​e​d​b​a​c​k​s
	 */
	Number_of_Feedbacks: string
	/**
	 * A​v​e​r​a​g​e​ ​l​i​n​e​a​r​ ​r​a​t​i​n​g​s
	 */
	Average_linear_ratings: string
	/**
	 * v​o​t​e​s
	 */
	votes: string
	/**
	 * P​r​i​v​a​t​e​ ​B​i​n​g​o
	 */
	Private_Bingo: string
	/**
	 * M​y​ ​t​a​l​k​s​ ​w​i​t​h​ ​f​e​e​d​b​a​c​k​s
	 */
	My_talks_with_Feedbacks: string
	/**
	 * *​O​n​g​o​i​n​g​*​ ​e​v​e​n​t​s
	 */
	Ongoing_events_highlighted: string
	/**
	 * *​F​u​t​u​r​e​*​ ​e​v​e​n​t​s
	 */
	Future_events_highlighted: string
	/**
	 * *​P​a​s​t​*​ ​e​v​e​n​t​s
	 */
	Past_events_highlighted: string
	/**
	 * F​u​t​u​r​e​ ​e​v​e​n​t​s
	 */
	Future_events: string
	/**
	 * P​a​s​t​ ​e​v​e​n​t​s
	 */
	Past_events: string
	/**
	 * N​e​w​ ​c​o​n​t​e​n​t​ ​a​v​a​i​l​a​b​l​e​.​ ​C​l​i​c​k​ ​o​n​ ​r​e​l​o​a​d​ ​b​u​t​t​o​n​ ​t​o​ ​u​p​d​a​t​e​ ​i​n​ ​b​a​c​k​g​r​o​u​n​d​ ​t​h​e​n​ ​a​u​t​o​-​r​e​l​o​a​d​ ​p​a​g​e​ ​o​n​c​e​ ​c​o​n​t​e​n​t​ ​i​s​ ​d​o​w​n​l​o​a​d​e​d​.
	 */
	New_content_available_click_on_reload_button_to_update: string
	/**
	 * R​e​l​o​a​d
	 */
	Reload: string
	/**
	 * N​o​ ​t​a​l​k​s​ ​f​o​u​n​d​ ​f​o​r​ ​s​e​l​e​c​t​e​d​ ​d​a​y
	 */
	No_talks_matching_search_terms: string
	/**
	 * S​o​c​i​a​l​ ​m​e​d​i​a
	 */
	Social_media: string
	/**
	 * E​v​e​n​t​ ​p​l​a​n​s
	 */
	Event_plans: string
	/**
	 * E​v​e​n​t​ ​s​u​m​m​a​r​y
	 */
	Event_summary: string
	/**
	 * S​p​o​n​s​o​r​s
	 */
	Sponsors: string
	/**
	 * P​l​e​a​s​e​ ​k​e​e​p​ ​t​h​i​s​ ​t​o​k​e​n​ ​p​r​i​v​a​t​e
	 */
	Please_keep_this_token_private: string
	/**
	 * U​s​e​r​ ​u​i​d
	 */
	User_uid: string
	/**
	 * P​r​o​f​i​l​e
	 */
	Profile: string
	/**
	 * L​o​g​o​u​t
	 */
	Logout: string
	/**
	 * A​n​o​n​y​m​o​u​s​ ​(​p​r​i​v​a​t​e​)​ ​u​s​e​r​ ​t​o​k​e​n
	 */
	Anonymous_private_user_id: string
	/**
	 * P​u​b​l​i​c​ ​u​s​e​r​ ​t​o​k​e​n
	 */
	Public_user_id: string
	/**
	 * H​o​w​ ​a​n​d​ ​w​h​e​r​e​ ​c​a​n​ ​I​ ​c​o​n​t​a​c​t​ ​t​h​e​ ​t​e​a​m​ ​?
	 */
	How_and_where_can_I_contact_the_team: string
	/**
	 * T​h​i​s​ ​t​o​k​e​n​ ​w​i​l​l​ ​b​e​ ​u​s​e​d​ ​t​o​ ​(​a​n​o​n​y​m​o​u​s​l​y​)​ ​r​e​f​e​r​e​n​c​e​ ​y​o​u​ ​i​n​ ​f​e​e​d​b​a​c​k​s
	 */
	This_token_will_be_used_to_reference_you_in_APIs: string
	/**
	 * A​p​p​ ​s​e​t​t​i​n​g​s
	 */
	App_settings: string
	/**
	 * C​o​n​f​i​g​u​r​e​ ​m​y​ ​p​r​e​f​e​r​e​n​c​e​s​ ​a​p​p
	 */
	Configure_my_preferences_app: string
	/**
	 * F​r​e​q​u​e​n​t​l​y​ ​a​s​k​e​d​ ​q​u​e​s​t​i​o​n​s
	 */
	Frequently_asked_questions: string
}

export type TranslationFunctions = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
	 */
	HI: (arg: { name: string }) => LocalizedString
	/**
	 * Open user dashboard
	 */
	Open_User_Dashboard: () => LocalizedString
	/**
	 * Close
	 */
	Close: () => LocalizedString
	/**
	 * Previous screen
	 */
	Previous_screen: () => LocalizedString
	/**
	 * Back dashboard
	 */
	Back_User_Dashboard: () => LocalizedString
	/**
	 * Avatar speaker
	 */
	Avatar_Speaker: () => LocalizedString
	/**
	 * Back
	 */
	Nav_Back: () => LocalizedString
	/**
	 * Conference Selector
	 */
	Conference_Selector: () => LocalizedString
	/**
	 * Pinned events
	 */
	Pinned_events: () => LocalizedString
	/**
	 * Configuration event
	 */
	Config_event: () => LocalizedString
	/**
	 * Back to events list
	 */
	Back_List_Events: () => LocalizedString
	/**
	 * Logo
	 */
	Logo_event: () => LocalizedString
	/**
	 * No pinned events available yet
	 */
	No_pinned_events_available_yet: () => LocalizedString
	/**
	 * No conference registered yet
	 */
	No_conference_registered_yet: () => LocalizedString
	/**
	 * Search a conference
	 */
	Search_a_conference: () => LocalizedString
	/**
	 * Keywords
	 */
	Keywords: () => LocalizedString
	/**
	 * Actions
	 */
	Actions: () => LocalizedString
	/**
	 * Remove from pinned events
	 */
	Remove_from_pinned_events: () => LocalizedString
	/**
	 * Add to my pinned events
	 */
	Add_to_my_pinned_events: () => LocalizedString
	/**
	 * Visit website
	 */
	Visit_website: () => LocalizedString
	/**
	 * Cancel
	 */
	Cancel: () => LocalizedString
	/**
	 * Schedule
	 */
	Schedule: () => LocalizedString
	/**
	 * Banner event
	 */
	Banner_Event: () => LocalizedString
	/**
	 * Cancel and back to schedule page
	 */
	Cancel_Back_To_Schedule: () => LocalizedString
	/**
	 * Search
	 */
	Search: () => LocalizedString
	/**
	 * Close search
	 */
	Search_close: () => LocalizedString
	/**
	 * Filters
	 */
	Filters: () => LocalizedString
	/**
	 * Add to Watch later
	 */
	Add_Watch_later: () => LocalizedString
	/**
	 * Removed from watch later
	 */
	Remove_Watch_later: () => LocalizedString
	/**
	 * Add to favorites
	 */
	Add_Favorites: () => LocalizedString
	/**
	 * Removed from favorites
	 */
	Remove_Favorites: () => LocalizedString
	/**
	 * Favorites
	 */
	Favorites: () => LocalizedString
	/**
	 * Feedbacks
	 */
	Feedbacks: () => LocalizedString
	/**
	 * No feedback yet
	 */
	No_feedback_yet: () => LocalizedString
	/**
	 * Infos
	 */
	Infos: () => LocalizedString
	/**
	 * Ongoing
	 */
	ConfStatus_ongoing: () => LocalizedString
	/**
	 * Past
	 */
	ConfStatus_past: () => LocalizedString
	/**
	 * Future
	 */
	ConfStatus_future: () => LocalizedString
	/**
	 * Unknown
	 */
	ConfStatus_unknown: () => LocalizedString
	/**
	 * overlaps
	 */
	Overlaps_x_slot_label: () => LocalizedString
	/**
	 * {nrOfOverlappingSlots} slot{{s}}
	 */
	Overlaps_x_slot_value: (arg: { nrOfOverlappingSlots: number }) => LocalizedString
	/**
	 * Talk summary
	 */
	Talk_summary: () => LocalizedString
	/**
	 * Talk details
	 */
	Talk_details: () => LocalizedString
	/**
	 * Close talk details
	 */
	Close_talk_details: () => LocalizedString
	/**
	 * Speakers
	 */
	Speakers: () => LocalizedString
	/**
	 * Go to ticketing
	 */
	Go_To_Ticketing: () => LocalizedString
	/**
	 * Like speaker
	 */
	Like_Speaker: () => LocalizedString
	/**
	 * Big list mode
	 */
	Big_list_mode: () => LocalizedString
	/**
	 * Compact list mode
	 */
	Compact_list_mode: () => LocalizedString
	/**
	 * See the speaker's page
	 */
	View_Profil_Speaker: () => LocalizedString
	/**
	 * Welcome to
	 */
	Welcome_to: () => LocalizedString
	/**
	 * Hello, {name}
	 */
	Hello_xxx: (arg: { name: string }) => LocalizedString
	/**
	 * Add from the list below
	 */
	Add_from_the_list_below: () => LocalizedString
	/**
	 * View day
	 */
	View_day: () => LocalizedString
	/**
	 * Today
	 */
	Today: () => LocalizedString
	/**
	 * Tomorrow
	 */
	Tomorrow: () => LocalizedString
	/**
	 * No favorites defined yet
	 */
	No_favorites_defined_yet: () => LocalizedString
	/**
	 * Info page still under construction
	 */
	Info_page_still_under_construction: () => LocalizedString
	/**
	 * Add Feedback
	 */
	Add_Feedback: () => LocalizedString
	/**
	 * Add Feedback on slot
	 */
	Add_Feedback_On_Slot: () => LocalizedString
	/**
	 * Open list of feedback slots
	 */
	Open_List_Slot_Feedback: () => LocalizedString
	/**
	 * Pick the talk you attended
	 */
	Pick_the_talk_you_attended: () => LocalizedString
	/**
	 * Select one of the talk you attended
	 */
	Select_one_of_the_talk_you_attended: () => LocalizedString
	/**
	 * Either select one of the talk you attended...
	 */
	Either_select_one_of_the_talk_you_attended: () => LocalizedString
	/**
	 * ... or select a talk in these overlapping slots
	 */
	Or_select_a_talk_in_these_overlapping_slots: () => LocalizedString
	/**
	 * Currently selected timeslot
	 */
	Currently_selected_timeslot: () => LocalizedString
	/**
	 * {nrOfOverlappingSlots} Overlapping time slot{{s}}
	 */
	Overlapping_timeslots: (arg: { nrOfOverlappingSlots: number }) => LocalizedString
	/**
	 * In favorites
	 */
	In_favorites: () => LocalizedString
	/**
	 * {nrOfNonFavoritedTalks|typedef-only}Show non-favorited talk{{s}}
	 */
	Show_non_favorited_talks: (arg: { nrOfNonFavoritedTalks: number }) => LocalizedString
	/**
	 * Watch later all favorited talks
	 */
	Watch_later_all_favorited_talks: () => LocalizedString
	/**
	 * I didn't attend any talk
	 */
	I_didnt_attend_any_talk: () => LocalizedString
	/**
	 * during this time slot
	 */
	During_this_time_slot: () => LocalizedString
	/**
	 * Share your feedback
	 */
	Share_your_feedback: () => LocalizedString
	/**
	 * Select for feedback
	 */
	Select_for_feedback: () => LocalizedString
	/**
	 * Rate it
	 */
	Rate_it: () => LocalizedString
	/**
	 * Quick Feedback
	 */
	Quick_feedback: () => LocalizedString
	/**
	 * Enter some constructive for the speaker
	 */
	Enter_some_constructive_feedback_for_the_speaker: () => LocalizedString
	/**
	 * Submit Feedback
	 */
	Submit_Feedback: () => LocalizedString
	/**
	 * Free comment
	 */
	Free_comment: () => LocalizedString
	/**
	 * Skipped
	 */
	Skipped: () => LocalizedString
	/**
	 * Settings list
	 */
	Settings_list: () => LocalizedString
	/**
	 * Hide today's past time-slots after 1h
	 */
	Hide_today_s_past_time_slots_after_1h: () => LocalizedString
	/**
	 * Hide past time-slots
	 */
	Hide_past_time_slots: () => LocalizedString
	/**
	 * Including slots without feedback
	 */
	Including_slots_without_feedback: () => LocalizedString
	/**
	 * Config
	 */
	Config: () => LocalizedString
	/**
	 * Talks
	 */
	Talks_Config: () => LocalizedString
	/**
	 * Open full version of the schedule
	 */
	Open_full_version_of_the_schedule: () => LocalizedString
	/**
	 * here
	 */
	Here: () => LocalizedString
	/**
	 * Feedbacks are not enabled on this event
	 */
	Feedbacks_are_not_enabled_on_this_event: () => LocalizedString
	/**
	 * Talk Feedbacks
	 */
	Talk_Feedbacks: () => LocalizedString
	/**
	 * Detailed Feedbacks
	 */
	Detailed_Feedbacks: () => LocalizedString
	/**
	 * Last updated
	 */
	Last_updated: () => LocalizedString
	/**
	 * Who
	 */
	Who: () => LocalizedString
	/**
	 * Linear rating
	 */
	Linear_rating: () => LocalizedString
	/**
	 * Level
	 */
	Linear_rating_level: () => LocalizedString
	/**
	 * Bingo
	 */
	Bingo: () => LocalizedString
	/**
	 * Custom rating
	 */
	Custom_rating: () => LocalizedString
	/**
	 * Stats
	 */
	Stats: () => LocalizedString
	/**
	 * Number of feedbacks
	 */
	Number_of_Feedbacks: () => LocalizedString
	/**
	 * Average linear ratings
	 */
	Average_linear_ratings: () => LocalizedString
	/**
	 * votes
	 */
	votes: () => LocalizedString
	/**
	 * Private Bingo
	 */
	Private_Bingo: () => LocalizedString
	/**
	 * My talks with feedbacks
	 */
	My_talks_with_Feedbacks: () => LocalizedString
	/**
	 * *Ongoing* events
	 */
	Ongoing_events_highlighted: () => LocalizedString
	/**
	 * *Future* events
	 */
	Future_events_highlighted: () => LocalizedString
	/**
	 * *Past* events
	 */
	Past_events_highlighted: () => LocalizedString
	/**
	 * Future events
	 */
	Future_events: () => LocalizedString
	/**
	 * Past events
	 */
	Past_events: () => LocalizedString
	/**
	 * New content available. Click on reload button to update in background then auto-reload page once content is downloaded.
	 */
	New_content_available_click_on_reload_button_to_update: () => LocalizedString
	/**
	 * Reload
	 */
	Reload: () => LocalizedString
	/**
	 * No talks found for selected day
	 */
	No_talks_matching_search_terms: () => LocalizedString
	/**
	 * Social media
	 */
	Social_media: () => LocalizedString
	/**
	 * Event plans
	 */
	Event_plans: () => LocalizedString
	/**
	 * Event summary
	 */
	Event_summary: () => LocalizedString
	/**
	 * Sponsors
	 */
	Sponsors: () => LocalizedString
	/**
	 * Please keep this token private
	 */
	Please_keep_this_token_private: () => LocalizedString
	/**
	 * User uid
	 */
	User_uid: () => LocalizedString
	/**
	 * Profile
	 */
	Profile: () => LocalizedString
	/**
	 * Logout
	 */
	Logout: () => LocalizedString
	/**
	 * Anonymous (private) user token
	 */
	Anonymous_private_user_id: () => LocalizedString
	/**
	 * Public user token
	 */
	Public_user_id: () => LocalizedString
	/**
	 * How and where can I contact the team ?
	 */
	How_and_where_can_I_contact_the_team: () => LocalizedString
	/**
	 * This token will be used to (anonymously) reference you in feedbacks
	 */
	This_token_will_be_used_to_reference_you_in_APIs: () => LocalizedString
	/**
	 * App settings
	 */
	App_settings: () => LocalizedString
	/**
	 * Configure my preferences app
	 */
	Configure_my_preferences_app: () => LocalizedString
	/**
	 * Frequently asked questions
	 */
	Frequently_asked_questions: () => LocalizedString
}

export type Formatters = {
	'typedef-only': (value: number) => unknown
}
