// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​i​ ​{​n​a​m​e​}​!​ ​P​l​e​a​s​e​ ​l​e​a​v​e​ ​a​ ​s​t​a​r​ ​i​f​ ​y​o​u​ ​l​i​k​e​ ​t​h​i​s​ ​p​r​o​j​e​c​t​:​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​i​v​a​n​h​o​f​e​r​/​t​y​p​e​s​a​f​e​-​i​1​8​n
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * C​o​n​f​e​r​e​n​c​e​ ​S​e​l​e​c​t​o​r
	 */
	Conference_Selector: string
	/**
	 * P​i​n​n​e​d​ ​e​v​e​n​t​s
	 */
	Pinned_events: string
	/**
	 * N​o​ ​p​i​n​n​e​d​ ​e​v​e​n​t​s​ ​a​v​a​i​l​a​b​l​e​ ​y​e​t
	 */
	No_pinned_events_available_yet: string
	/**
	 * N​o​ ​c​o​n​f​e​r​e​n​c​e​ ​r​e​g​i​s​t​e​r​e​d​ ​y​e​t
	 */
	No_conference_registered_yet: string
	/**
	 * P​a​s​t​ ​e​v​e​n​t​s
	 */
	Past_events: string
	/**
	 * S​e​a​r​c​h​ ​a​ ​c​o​n​f​e​r​e​n​c​e
	 */
	Search_a_conference: string
	/**
	 * K​e​y​w​o​r​d​s
	 */
	Keywords: string
	/**
	 * A​c​t​i​o​n​s
	 */
	Actions: string
	/**
	 * R​e​m​o​v​e​ ​f​r​o​m​ ​p​i​n​n​e​d​ ​e​v​e​n​t​s
	 */
	Remove_from_pinned_events: string
	/**
	 * A​d​d​ ​t​o​ ​m​y​ ​p​i​n​n​e​d​ ​e​v​e​n​t​s
	 */
	Add_to_my_pinned_events: string
	/**
	 * V​i​s​i​t​ ​w​e​b​s​i​t​e
	 */
	Visit_website: string
	/**
	 * C​a​n​c​e​l
	 */
	Cancel: string
	/**
	 * S​c​h​e​d​u​l​e
	 */
	Schedule: string
	/**
	 * S​e​a​r​c​h
	 */
	Search: string
	/**
	 * F​a​v​o​r​i​t​e​s
	 */
	Favorites: string
	/**
	 * F​e​e​d​b​a​c​k​s
	 */
	Feedbacks: string
	/**
	 * N​o​ ​f​e​e​d​b​a​c​k​ ​y​e​t
	 */
	No_feedback_yet: string
	/**
	 * I​n​f​o​s
	 */
	Infos: string
	/**
	 * O​n​g​o​i​n​g
	 */
	ConfStatus_ongoing: string
	/**
	 * P​a​s​t
	 */
	ConfStatus_past: string
	/**
	 * F​u​t​u​r​e
	 */
	ConfStatus_future: string
	/**
	 * U​n​k​n​o​w​n
	 */
	ConfStatus_unknown: string
	/**
	 * o​v​e​r​l​a​p​s
	 */
	Overlaps_x_slot_label: string
	/**
	 * {​n​r​O​f​O​v​e​r​l​a​p​p​i​n​g​S​l​o​t​s​}​ ​s​l​o​t​{​{​s​}​}
	 * @param {string | number | boolean} nrOfOverlappingSlots
	 */
	Overlaps_x_slot_value: RequiredParams<'nrOfOverlappingSlots'>
	/**
	 * T​a​l​k​ ​s​u​m​m​a​r​y
	 */
	Talk_summary: string
	/**
	 * T​a​l​k​ ​d​e​t​a​i​l​s
	 */
	Talk_details: string
	/**
	 * S​p​e​a​k​e​r​s
	 */
	Speakers: string
	/**
	 * W​e​l​c​o​m​e​ ​t​o
	 */
	Welcome_to: string
	/**
	 * H​e​l​l​o​,​ ​{​n​a​m​e​}
	 * @param {string} name
	 */
	Hello_xxx: RequiredParams<'name'>
	/**
	 * A​d​d​ ​f​r​o​m​ ​t​h​e​ ​l​i​s​t​ ​b​e​l​o​w
	 */
	Add_from_the_list_below: string
	/**
	 * T​o​d​a​y
	 */
	Today: string
	/**
	 * T​o​m​o​r​r​o​w
	 */
	Tomorrow: string
	/**
	 * F​a​v​o​r​i​t​e​d​ ​s​c​h​e​d​u​l​e​ ​n​o​t​ ​i​m​p​l​e​m​e​n​t​e​d​ ​(​y​e​t​)
	 */
	Favorited_schedule_not_implemented_yet: string
	/**
	 * I​n​f​o​ ​p​a​g​e​ ​s​t​i​l​l​ ​u​n​d​e​r​ ​c​o​n​s​t​r​u​c​t​i​o​n
	 */
	Info_page_still_under_construction: string
	/**
	 * A​d​d​ ​F​e​e​d​b​a​c​k
	 */
	Add_Feedback: string
	/**
	 * P​i​c​k​ ​t​h​e​ ​t​a​l​k​ ​y​o​u​ ​a​t​t​e​n​d​e​d
	 */
	Pick_the_talk_you_attended: string
	/**
	 * C​u​r​r​e​n​t​l​y​ ​s​e​l​e​c​t​e​d​ ​t​i​m​e​s​l​o​t
	 */
	Currently_selected_timeslot: string
	/**
	 * {​n​r​O​f​O​v​e​r​l​a​p​p​i​n​g​S​l​o​t​s​}​ ​O​v​e​r​l​a​p​p​i​n​g​ ​t​i​m​e​ ​s​l​o​t​{​{​s​}​}
	 * @param {string | number | boolean} nrOfOverlappingSlots
	 */
	Overlapping_timeslots: RequiredParams<'nrOfOverlappingSlots'>
	/**
	 * I​n​ ​f​a​v​o​r​i​t​e​s
	 */
	In_favorites: string
	/**
	 * S​h​o​w​ ​n​o​n​-​f​a​v​o​r​i​t​e​d​ ​t​a​l​k​{​{​s​}​}
	 */
	Show_non_favorited_talks: string
	/**
	 * W​a​t​c​h​ ​l​a​t​e​r​ ​a​l​l​ ​f​a​v​o​r​i​t​e​d​ ​t​a​l​k​s
	 */
	Watch_later_all_favorited_talks: string
	/**
	 * I​ ​d​i​d​n​'​t​ ​a​t​t​e​n​d​ ​a​n​y​ ​t​a​l​k
	 */
	I_didnt_attend_any_talk: string
	/**
	 * D​u​r​i​n​g​ ​t​h​i​s​ ​t​i​m​e​ ​s​l​o​t
	 */
	During_this_time_slot: string
	/**
	 * S​h​a​r​e​ ​y​o​u​r​ ​f​e​e​d​b​a​c​k
	 */
	Share_your_feedback: string
	/**
	 * R​a​t​e​ ​i​t
	 */
	Rate_it: string
	/**
	 * Q​u​i​c​k​ ​F​e​e​d​b​a​c​k
	 */
	Quick_feedback: string
	/**
	 * E​n​t​e​r​ ​s​o​m​e​ ​c​o​n​s​t​r​u​c​t​i​v​e​ ​f​o​r​ ​t​h​e​ ​s​p​e​a​k​e​r
	 */
	Enter_some_constructive_feedback_for_the_speaker: string
	/**
	 * S​u​b​m​i​t​ ​F​e​e​d​b​a​c​k
	 */
	Submit_Feedback: string
	/**
	 * F​r​e​e​ ​c​o​m​m​e​n​t
	 */
	Free_comment: string
}

export type TranslationFunctions = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
	 */
	HI: (arg: { name: string }) => LocalizedString
	/**
	 * Conference Selector
	 */
	Conference_Selector: () => LocalizedString
	/**
	 * Pinned events
	 */
	Pinned_events: () => LocalizedString
	/**
	 * No pinned events available yet
	 */
	No_pinned_events_available_yet: () => LocalizedString
	/**
	 * No conference registered yet
	 */
	No_conference_registered_yet: () => LocalizedString
	/**
	 * Past events
	 */
	Past_events: () => LocalizedString
	/**
	 * Search a conference
	 */
	Search_a_conference: () => LocalizedString
	/**
	 * Keywords
	 */
	Keywords: () => LocalizedString
	/**
	 * Actions
	 */
	Actions: () => LocalizedString
	/**
	 * Remove from pinned events
	 */
	Remove_from_pinned_events: () => LocalizedString
	/**
	 * Add to my pinned events
	 */
	Add_to_my_pinned_events: () => LocalizedString
	/**
	 * Visit website
	 */
	Visit_website: () => LocalizedString
	/**
	 * Cancel
	 */
	Cancel: () => LocalizedString
	/**
	 * Schedule
	 */
	Schedule: () => LocalizedString
	/**
	 * Search
	 */
	Search: () => LocalizedString
	/**
	 * Favorites
	 */
	Favorites: () => LocalizedString
	/**
	 * Feedbacks
	 */
	Feedbacks: () => LocalizedString
	/**
	 * No feedback yet
	 */
	No_feedback_yet: () => LocalizedString
	/**
	 * Infos
	 */
	Infos: () => LocalizedString
	/**
	 * Ongoing
	 */
	ConfStatus_ongoing: () => LocalizedString
	/**
	 * Past
	 */
	ConfStatus_past: () => LocalizedString
	/**
	 * Future
	 */
	ConfStatus_future: () => LocalizedString
	/**
	 * Unknown
	 */
	ConfStatus_unknown: () => LocalizedString
	/**
	 * overlaps
	 */
	Overlaps_x_slot_label: () => LocalizedString
	/**
	 * {nrOfOverlappingSlots} slot{{s}}
	 */
	Overlaps_x_slot_value: (arg: { nrOfOverlappingSlots: string | number | boolean }) => LocalizedString
	/**
	 * Talk summary
	 */
	Talk_summary: () => LocalizedString
	/**
	 * Talk details
	 */
	Talk_details: () => LocalizedString
	/**
	 * Speakers
	 */
	Speakers: () => LocalizedString
	/**
	 * Welcome to
	 */
	Welcome_to: () => LocalizedString
	/**
	 * Hello, {name}
	 */
	Hello_xxx: (arg: { name: string }) => LocalizedString
	/**
	 * Add from the list below
	 */
	Add_from_the_list_below: () => LocalizedString
	/**
	 * Today
	 */
	Today: () => LocalizedString
	/**
	 * Tomorrow
	 */
	Tomorrow: () => LocalizedString
	/**
	 * Favorited schedule not implemented (yet)
	 */
	Favorited_schedule_not_implemented_yet: () => LocalizedString
	/**
	 * Info page still under construction
	 */
	Info_page_still_under_construction: () => LocalizedString
	/**
	 * Add Feedback
	 */
	Add_Feedback: () => LocalizedString
	/**
	 * Pick the talk you attended
	 */
	Pick_the_talk_you_attended: () => LocalizedString
	/**
	 * Currently selected timeslot
	 */
	Currently_selected_timeslot: () => LocalizedString
	/**
	 * {nrOfOverlappingSlots} Overlapping time slot{{s}}
	 */
	Overlapping_timeslots: (arg: { nrOfOverlappingSlots: string | number | boolean }) => LocalizedString
	/**
	 * In favorites
	 */
	In_favorites: () => LocalizedString
	/**
	 * Show non-favorited talk{{s}}
	 */
	Show_non_favorited_talks: (arg: { nrOfNonFavoritedTalks: number | string | boolean }) => LocalizedString
	/**
	 * Watch later all favorited talks
	 */
	Watch_later_all_favorited_talks: () => LocalizedString
	/**
	 * I didn't attend any talk
	 */
	I_didnt_attend_any_talk: () => LocalizedString
	/**
	 * During this time slot
	 */
	During_this_time_slot: () => LocalizedString
	/**
	 * Share your feedback
	 */
	Share_your_feedback: () => LocalizedString
	/**
	 * Rate it
	 */
	Rate_it: () => LocalizedString
	/**
	 * Quick Feedback
	 */
	Quick_feedback: () => LocalizedString
	/**
	 * Enter some constructive for the speaker
	 */
	Enter_some_constructive_feedback_for_the_speaker: () => LocalizedString
	/**
	 * Submit Feedback
	 */
	Submit_Feedback: () => LocalizedString
	/**
	 * Free comment
	 */
	Free_comment: () => LocalizedString
}

export type Formatters = {}
